version: '3'
services:
    apache:
         container_name: webserver
         image: joseadiaz/apache
         ports:
             - '80:80'
         networks:
               HLC:
                 ipv4_address: 192.168.10.5
networks:
  HLC:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.10.0/24
