---
env:
  RUNLEVEL: 1

mysql_packages:
  - python-selinux
  - mysql-server
  - python-mysqldb

mysql_service: mysql

mysql_conf_dir: "/etc/mysql"

repository: "deb http://repo.mysql.com/apt/debian/ jessie mysql-5.7"
